version: "3.7"

services:
  database:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: S123456s
      MYSQL_USER: sibel
      MYSQL_PASSWORD: Sibel_1
    networks:
      - sibelnet
  my-app:
    image: sibelozen/bookstore-api:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - sibelnet
networks:
  sibelnet:
    driver: bridge
